version: '3.4'

services:
  pus:
    image: ${DOCKER_REGISTRY-}pus
    build:
      context: .
      dockerfile: PUS/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.10.2
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: pus
      MYSQL_USER: pususer
      MYSQL_PASSWORD: secret
    restart: on-failure


#  db:
#    image: "mcr.microsoft.com/mssql/server:2022-latest"
#    ports:
#        - "1433:1433"
#
#    environment:
#        SA_PASSWORD: "Rafiki_19"
#        ACCEPT_EULA: "Y"
