version: '3.4'

services:
  pus:
    image: ${DOCKER_REGISTRY-}pus
    build:
      context: .
      dockerfile: PUS/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"

    environment:
        SA_PASSWORD: "Rafiki_19"
        ACCEPT_EULA: "Y"